packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/react": ^18.2.61
  "@types/react-dom": ^18.2.61
  "@vitejs/plugin-react": "4.2.1"
  "react": ^18.2.0
  "react-dom": ^18.2.0
  "typescript": ^5.5.3
  "vite": ^5.2.11
